---
deployment:
  tasks:
    # this path is fixed in cpanel, do not update
    - export DEPLOYPATH=/home/aidanhon/public_html/
    - export TESTDEPLOYPATH=/home/aidanhon/test_html/
    - export TEST_BRANCH=test
    - export PROD_BRANCH=mainline
    - export CURRENT_BRANCH=$(git symbolic-ref --short HEAD)
    - if [ ${CURRENT_BRANCH} == ${TEST_BRANCH} ]; then /bin/cp -R dist/browser/* $TESTDEPLOYPATH; elif [ ${CURRENT_BRANCH} == ${PROD_BRANCH} ]; then /bin/cp -R dist/browser/* $DEPLOYPATH; else echo "Could not determine proper deployment location"; fi
