name: AidanHonan.com Deployment Pipeline

on: 
  push:
    branches:
      - mainline

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm ci
      - name: Build and test
        run: npm run build
      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: deploy_dist
          path: dist/browser
          include-hidden-files: true
      - name: Archive code coverage result
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: deploy_coverage
          path: coverage
        
  deploy-beta:
    name: Deploy Beta Site
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: deploy_dist
          path: deploy_dist
      - name: Deploy to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftps.aidanhonan.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          server-dir: test/
          local-dir: ./deploy_dist/
          dry-run: false

  beta-approval-workflow:
    name: Beta Approval Workflow
    needs: deploy-beta
    runs-on: ubuntu-latest
    steps:
      - name: Beta Integ Test Placeholder
        run: echo "Placeholder for Beta Integ Tests"
      - name: Manual Approval PlaceHolder
        run: echo "See link to set up - https://github.com/marketplace/actions/manual-workflow-approval"

  deploy-prod:
    name: Deploy Prod Site
    needs: beta-approval-workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: deploy_dist
          path: deploy_dist
      - name: Deploy to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftps.aidanhonan.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          local-dir: ./deploy_dist/
          dry-run: false
          exclude: |
            **/test/**
            **/.well-known/**
            **/cgi-bin/**
            .ftpquota
            a2-default-index.php
  
  prod-approval-workflow:
    name: Prod Approval Workflow
    needs: deploy-prod
    runs-on: ubuntu-latest
    steps:
      - name: Prod Integ Test Placeholder
        run: echo "Placeholder for Prod Integ Tests"