name: PR Validation

on:
  pull_request:
    types: [opened, reopened]

jobs:
  dependency_review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/dependency-review-action@v4

  dry_run_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        id: install_deps
        run: npm install

      - name: Dump version
        if: steps.install_deps.outcome == 'success'
        run: |
          node -v
          npm --version
          git --version
          ng --version

      - name: Build
        if: steps.install_deps.outcome == 'success'
        run: npm run build
