name: PR Validation

on:
  pull_request:
    types: [opened, reopened]

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test Job
        uses: colbyhill21/angular-full-ci@v1.0
        with:
          # Command to run tests on your project, do not prepend with "npm", it is already included.
          testcommand: run test:ci
